### ISSUE TITLE
Program 0.1.2-beta testing-01 Results and Requests

### ISSUE THREAD

**Issue by yoantran** [miketvo/imdupes-prototype#16]
version: imdupes 0.1.2-beta

1. Tested `scan` on a phone's photos folder of 8,987 Files, and 67 Folders/Sub-Folders (including .jpg, .png, .mp4, .AAE, .jpeg, .gif):

- only jpg, jpeg, png can be detected rn

- currently no issues found.

3. Tested `scan` on an art folder of 6,502 Files, and 242 Folders/Sub-Folders (including .jpg, .png,. .psd, .clip, .sai, .txt, .jfif, .tmp, .gif, .cmc, .rif):

- only jpg, jpeg, png can be detected right now.

- can't differentiate: black filled canvas vs. black-color elements on transparent canvas vs. black rectangle on white canvas vs. white elements on transparent canvas. e.g. some examples detected and listed in DUPLICATION 1:
![list_Untitled184](https://github.com/miketvo/imdupes-prototype/assets/92938451/253e480c-c26c-4e14-9dc1-dde45a7f9d0f)
![list_Untitled203](https://github.com/miketvo/imdupes-prototype/assets/92938451/e7c3b887-1c66-46cf-803b-11a8910bb757)
![a](https://github.com/miketvo/imdupes-prototype/assets/92938451/293ff113-92d4-4762-be28-dbf3c16b5986)
![math-transparent-background-1](https://github.com/miketvo/imdupes-prototype/assets/92938451/7e7cc582-81bc-4c5b-8f12-43ffa860c1cc)

- can't detect a small detail changed between canvas (right now it is useful for me to detect duplicated outcome of my art with just a few pixels changed eg. nose, blushes, mouth curve, an art with blurred bg and an art without blurred bg, etc. and i would decide to keep some of them)

- can't detect grey-scale. The examples are detected as duplication by the program (see the top-right of the pictures) while they have different color values. e.g:
![logo](https://github.com/miketvo/imdupes-prototype/assets/92938451/939cee81-ccfe-4229-b88b-294b4659338d)
![watermark](https://github.com/miketvo/imdupes-prototype/assets/92938451/0f10bf6a-d6ec-4bde-8f1f-c6753220b7d2)
There is another example but I will send privately because this one is a commission.

4. Need clearer instruction for dummies:
- Personally, it took me a while to know how to use.
- Some simple examples behind an input could help for a non-coder like me.

> can improve on the opt to choose to detect dup with same or different size

> have not tested on `clean` yet

**Comment by miketvo** [comment]
![image](https://github.com/miketvo/imdupes-prototype/assets/73817896/c314ab80-f080-48ee-8d0e-23d0d9cd2213)
imdupes can still detect and read `.gif` image fine, but the program is too accurate, to the point that even slight difference in image compression method would produce a different hash. So to identical `.gif` files would be detected as duplication
but between a `.gif` file and a `.jpg` file that both contain the same image, imdupes would think they're different, because of how the image is compressed in each format:

`.gif` format is uncompressed, but only has 256 available colors per pixel, while `.jpg` is compressed --> will create very slight color glitches, unnoticeable by human eyes, but will be noticed by the program, plus, the color range of each pixel may be larger than 256 (if 16-bit image for example), which is why imdupes doesn't think they're the same image.

**Comment by miketvo** [comment]
For the issue of differentiating between transparent and solid colors, I am working on a RGB/RGBA sensitive hashing method (#23) which will be available in the next release.

**Comment by miketvo** [comment]
I appreciate your feedback a lot @yoantran 😸 It has been very helpful!

**Comment by miketvo** [comment]
In summary, your inquiry can actually be considered as a feature request, with the next release (#27) satisfying your requirements.

**Comment by yoantran** [comment]
> I appreciate your feedback a lot @yoantran 😸 It has been very helpful!

I am glad my feedback could help ^^
